-- 1번
SELECT STUDENT_NO 학번 , STUDENT_NAME 이름 , TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 입학년도 
FROM TB_STUDENT ts 
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;


-- 2번
SELECT PROFESSOR_NAME , PROFESSOR_SSN 
FROM TB_PROFESSOR tp 
WHERE PROFESSOR_NAME NOT LIKE ('___');


-- 3번 !!
SELECT PROFESSOR_NAME 교수이름 ,  
	EXTRACT (YEAR FROM SYSDATE) - (TO_NUMBER(SUBSTR(PROFESSOR_SSN, 1, 2))+1900) 나이
FROM TB_PROFESSOR tp
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1' 
ORDER BY 나이;


SELECT PROFESSOR_NAME 교수이름 ,
 TRUNC(MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(PROFESSOR_SSN, 1, INSTR(PROFESSOR_SSN, '-')-1), 'RRMMDD'))/12) 나이	
FROM TB_PROFESSOR tp
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1' 
ORDER BY 나이;


-- 4번
SELECT SUBSTR(PROFESSOR_NAME, 2) 이름 
FROM TB_PROFESSOR tp;


-- 5번 !!
SELECT STUDENT_NO , STUDENT_NAME 
FROM TB_STUDENT ts 
WHERE TRUNC(MONTHS_BETWEEN( ENTRANCE_DATE,
TO_DATE( SUBSTR(STUDENT_SSN, 1, INSTR(STUDENT_SSN, '-')-1), 'RRMMDD' ) ) / 12) > 19; 


-- 6번
SELECT TO_CHAR(TO_DATE('2020-12-25'), 'DAY') FROM DUAL;


-- 7번
SELECT TO_DATE('99/10/11', 'YY/MM/DD') , TO_DATE('49/10/11', 'YY/MM/DD') ,
	TO_DATE('99/10/11', 'RR/MM/DD') , TO_DATE('49/10/11', 'RR/MM/DD')
FROM DUAL;


-- 8번
SELECT STUDENT_NO , STUDENT_NAME 
FROM TB_STUDENT ts 
WHERE EXTRACT (YEAR FROM ENTRANCE_DATE) < 2000;


-- 9번
SELECT ROUND(AVG(POINT), 1) 평점 
FROM TB_GRADE tg 
WHERE STUDENT_NO = 'A517178'


-- 10번
SELECT DEPARTMENT_NO 학과번호 , COUNT(*) "학생수(명)" 
FROM TB_STUDENT ts 
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;


-- 11번
SELECT COUNT(*) 
FROM TB_STUDENT ts 
WHERE COACH_PROFESSOR_NO IS NULL; 


-- 12번
SELECT SUBSTR(TERM_NO, 1, 4) 년도 ,  ROUND(AVG(POINT), 1) 
FROM TB_GRADE tg 
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4);


-- 13번 !!
SELECT DEPARTMENT_NO , COUNT(*) 
FROM TB_STUDENT ts 
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

SELECT DEPARTMENT_NO
FROM TB_STUDENT ts 
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

SELECT DEPARTMENT_NO, DECODE(ABSENCE_YN, 'N', NULL, 'Y', 'Y') ABSENCE_YN , COUNT(*) 
FROM TB_STUDENT ts 
GROUP BY DEPARTMENT_NO, ABSENCE_YN
ORDER BY DEPARTMENT_NO;

SELECT DEPARTMENT_NO, COUNT(*) 
FROM TB_STUDENT ts 
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;


-- 14번
SELECT STUDENT_NAME , COUNT(*) 
FROM TB_STUDENT ts 
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1 
ORDER BY STUDENT_NAME; 


-- 15번 !!
SELECT SUBSTR(TERM_NO, 1, 4) 년도 , SUBSTR(TERM_NO, 5) 학기,  POINT 평점
FROM TB_GRADE tg 
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, 5), POINT;

















