-- 1번
SELECT TS.STUDENT_NAME "학생 이름", TS.STUDENT_ADDRESS "주소지"
FROM TB_STUDENT ts
ORDER BY 1;


-- 2번
SELECT TS.STUDENT_NAME , TS.STUDENT_SSN 
FROM TB_STUDENT ts 
WHERE TS.ABSENCE_YN = 'Y'
ORDER BY 2 DESC;


-- 3번
SELECT TS.STUDENT_NAME "학생이름" , TS.STUDENT_NO "학번" , TS.STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT ts 
WHERE (TS.STUDENT_ADDRESS LIKE '강원도%' OR TS.STUDENT_ADDRESS LIKE '경기도%')
AND TS.STUDENT_NO LIKE '9%'
ORDER BY 1;


-- 4번
SELECT TP.PROFESSOR_NAME , TP.PROFESSOR_SSN  
FROM TB_PROFESSOR tp 
JOIN TB_DEPARTMENT td USING (DEPARTMENT_NO)
WHERE TD.DEPARTMENT_NAME = '법학과'
ORDER BY 2;


-- 5번
SELECT STUDENT_NO , TO_CHAR( TG.POINT , '9.99') "POINT" 
FROM TB_STUDENT ts 
JOIN TB_GRADE tg USING (STUDENT_NO)
WHERE TG.CLASS_NO = 'C3118100'
AND TG.TERM_NO = '200402'
ORDER BY 2 DESC;


-- 6번
SELECT TS.STUDENT_NO , TS.STUDENT_NAME , TD.DEPARTMENT_NAME 
FROM TB_STUDENT ts 
JOIN TB_DEPARTMENT td USING (DEPARTMENT_NO);


-- 7번
SELECT TC.CLASS_NAME , TD.DEPARTMENT_NAME 
FROM TB_CLASS tc 
JOIN TB_DEPARTMENT td USING (DEPARTMENT_NO);


-- 8번 !!!
-- CLASS 882, CLASS-PROFESSOR 776, PROFESSOR 114
SELECT TC.CLASS_NAME , TP.PROFESSOR_NAME 
FROM TB_CLASS tc 
JOIN TB_PROFESSOR tp USING (DEPARTMENT_NO); -- 1575

SELECT TC.CLASS_NAME , TP.PROFESSOR_NAME 
FROM TB_CLASS tc 
JOIN TB_CLASS_PROFESSOR tcp USING (CLASS_NO)
JOIN TB_PROFESSOR tp USING (PROFESSOR_NO); -- 776

SELECT TC.CLASS_NAME , TP.PROFESSOR_NAME 
FROM TB_CLASS tc 
JOIN TB_CLASS_PROFESSOR tcp ON (TC.CLASS_NO = TCP.CLASS_NO)
JOIN TB_PROFESSOR tp ON (TCP.PROFESSOR_NO = TP.PROFESSOR_NO);


-- 9번
SELECT TC.CLASS_NAME , TP.PROFESSOR_NAME 
FROM TB_CLASS tc 
JOIN TB_CLASS_PROFESSOR tcp ON (TC.CLASS_NO = TCP.CLASS_NO)
JOIN TB_PROFESSOR tp ON (TCP.PROFESSOR_NO = TP.PROFESSOR_NO)
JOIN TB_DEPARTMENT td ON (TP.DEPARTMENT_NO = TD.DEPARTMENT_NO)
WHERE TD.CATEGORY = '인문사회';


-- 10번
SELECT TS.STUDENT_NO 학번 , TS.STUDENT_NAME "학생 이름" , ROUND(AVG(TG.POINT), 1) "평점"
FROM TB_STUDENT ts 
LEFT JOIN TB_GRADE tg ON (TS.STUDENT_NO = TG.STUDENT_NO)
LEFT JOIN TB_DEPARTMENT td ON (TS.DEPARTMENT_NO = TD.DEPARTMENT_NO)
WHERE TD.DEPARTMENT_NAME = '음악학과'
GROUP BY TS.STUDENT_NO , TS.STUDENT_NAME
ORDER BY 1;


-- 11번
SELECT TD.DEPARTMENT_NAME "학과이름" , TS.STUDENT_NAME "학생이름" , TP.PROFESSOR_NAME "지도교수이름"
FROM TB_STUDENT ts 
JOIN TB_PROFESSOR tp ON (TS.COACH_PROFESSOR_NO = TP.PROFESSOR_NO)
JOIN TB_DEPARTMENT td ON (TS.DEPARTMENT_NO = TD.DEPARTMENT_NO)
WHERE TS.STUDENT_NO  = 'A313047';


-- 12번
SELECT TS.STUDENT_NAME , TG.TERM_NO 
FROM TB_STUDENT ts 
JOIN TB_GRADE tg ON (TS.STUDENT_NO = TG.STUDENT_NO)
JOIN TB_CLASS tc ON (TG.CLASS_NO = TC.CLASS_NO)
--JOIN TB_CLASS tc ON (TS.DEPARTMENT_NO = TC.DEPARTMENT_NO)
WHERE TC.CLASS_NAME = '인간관계론'
AND TG.TERM_NO LIKE '2007%';


-- 13번
SELECT TC.CLASS_NAME, TD.DEPARTMENT_NAME
FROM TB_CLASS tc 
LEFT JOIN TB_CLASS_PROFESSOR tcp USING (CLASS_NO)
JOIN TB_DEPARTMENT td USING (DEPARTMENT_NO)
WHERE TCP.PROFESSOR_NO IS NULL
AND TD.CATEGORY = '예체능';


-- 14번
SELECT TS.STUDENT_NAME "학생이름" , NVL(TP.PROFESSOR_NAME, '지도교수 미지정') "지도교수"
FROM TB_STUDENT ts 
LEFT JOIN TB_PROFESSOR tp ON (TS.COACH_PROFESSOR_NO = TP.PROFESSOR_NO)
LEFT JOIN TB_DEPARTMENT td ON (TS.DEPARTMENT_NO = TD.DEPARTMENT_NO)
WHERE TD.DEPARTMENT_NAME = '서반아어학과'
ORDER BY TS.STUDENT_NO;


-- 15번
SELECT TS.STUDENT_NO "학번" , TS.STUDENT_NAME "이름" , TD.DEPARTMENT_NAME "학과 이름" , AVG(TG.POINT) "평점"
FROM TB_STUDENT ts 
LEFT JOIN TB_DEPARTMENT td ON (TS.DEPARTMENT_NO = TD.DEPARTMENT_NO)
LEFT JOIN TB_GRADE tg ON (TS.STUDENT_NO = TG.STUDENT_NO)
WHERE TS.ABSENCE_YN = 'N'
GROUP BY TS.STUDENT_NO , TS.STUDENT_NAME , TD.DEPARTMENT_NAME 
HAVING AVG(TG.POINT) >= 4.0
ORDER BY 1;


-- 16번
SELECT TC.CLASS_NO , TC.CLASS_NAME , TRUNC(AVG(POINT), 8) "AVG(POINT)"
FROM TB_CLASS tc 
LEFT JOIN TB_GRADE tg ON (TC.CLASS_NO = TG.CLASS_NO)
LEFT JOIN TB_DEPARTMENT td ON (TC.DEPARTMENT_NO = TD.DEPARTMENT_NO)
WHERE TD.DEPARTMENT_NAME = '환경조경학과'
AND TC.CLASS_TYPE = '전공선택'
GROUP BY TC.CLASS_NO , TC.CLASS_NAME
ORDER BY TC.CLASS_NO ;


-- 17번
SELECT TS2.STUDENT_NAME , TS2.STUDENT_ADDRESS 
FROM TB_STUDENT ts 
LEFT JOIN TB_STUDENT ts2 ON(TS.DEPARTMENT_NO = TS2.DEPARTMENT_NO)
WHERE TS.STUDENT_NAME = '최경희';


-- 18번
SELECT TS.STUDENT_NO , TS.STUDENT_NAME
FROM TB_STUDENT ts 
LEFT JOIN TB_DEPARTMENT td ON (TS.DEPARTMENT_NO = TD.DEPARTMENT_NO)
LEFT JOIN TB_GRADE tg ON (TS.STUDENT_NO  = TG.STUDENT_NO)
WHERE TS.DEPARTMENT_NO = '001'
GROUP BY TS.STUDENT_NO , TS.STUDENT_NAME, TD.DEPARTMENT_NAME
HAVING AVG(POINT) = ( SELECT MAX(AVG(POINT)) 
					  FROM TB_STUDENT ts 
					  LEFT JOIN TB_DEPARTMENT td ON (TS.DEPARTMENT_NO = TD.DEPARTMENT_NO)
					  LEFT JOIN TB_GRADE tg ON (TS.STUDENT_NO  = TG.STUDENT_NO)
					  WHERE TS.DEPARTMENT_NO = '001'
					  GROUP BY TS.STUDENT_NO , TS.STUDENT_NAME, TD.DEPARTMENT_NAME);
					 
-- 19번
SELECT TD.DEPARTMENT_NAME "계열 학과명", ROUND(AVG(POINT), 1) "전공평점"
FROM TB_DEPARTMENT td 
LEFT JOIN TB_CLASS tc ON (TD.DEPARTMENT_NO = TC.DEPARTMENT_NO)
LEFT JOIN TB_GRADE tg ON (TC.CLASS_NO = TG.CLASS_NO)
WHERE TD.CATEGORY = '자연과학'
GROUP BY TD.DEPARTMENT_NAME 
ORDER BY 1;

