-- 1번
SELECT DEPARTMENT_NAME 학과명, CATEGORY 계열
FROM TB_DEPARTMENT td;


-- 2번
SELECT DEPARTMENT_NAME || '의 정원은 '|| CAPACITY || '명 입니다.' "학과별 정원"
FROM TB_DEPARTMENT td; 


-- 3번
SELECT STUDENT_NAME 
FROM TB_STUDENT ts
WHERE DEPARTMENT_NO = '001'
AND STUDENT_SSN LIKE '%-2%'
AND ABSENCE_YN = 'Y';


-- 4번
SELECT STUDENT_NAME 
FROM TB_STUDENT ts 
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NAME DESC;


-- 5번
SELECT DEPARTMENT_NAME , CATEGORY 
FROM TB_DEPARTMENT td 
WHERE CAPACITY BETWEEN 20 AND 30;


-- 6번
SELECT PROFESSOR_NAME 
FROM TB_PROFESSOR tp 
WHERE DEPARTMENT_NO IS NULL;


-- 7번
SELECT STUDENT_NAME 
FROM TB_STUDENT ts 
WHERE DEPARTMENT_NO IS NULL;


-- 8번
SELECT CLASS_NO 
FROM TB_CLASS tc 
WHERE PREATTENDING_CLASS_NO IS NOT NULL;


-- 9번
SELECT DISTINCT CATEGORY 
FROM TB_DEPARTMENT td
ORDER BY CATEGORY;

-- 10번
SELECT STUDENT_NO , STUDENT_NAME , STUDENT_SSN 
FROM TB_STUDENT ts 
WHERE ENTRANCE_DATE BETWEEN '2002-01-01' AND '2002-12-31'
AND STUDENT_ADDRESS LIKE '전주시%'
AND ABSENCE_YN <> 'Y';



SELECT STUDENT_NO , STUDENT_NAME , STUDENT_SSN 
FROM TB_STUDENT ts 
WHERE STUDENT_NO LIKE 'A2%'
AND STUDENT_ADDRESS LIKE '전주시%'
AND ABSENCE_YN <> 'Y'
ORDER BY STUDENT_NAME;







